import mongoose, { Schema, type Document, type Model } from "mongoose";
import type { ProductStatus } from "@/lib/constants";

export type ProductOrientation = "SINGLE" | "LEFT_RIGHT";

export interface IProduct extends Document {
  name: string;
  productCode: string;

  category: mongoose.Types.ObjectId;
  brand?: string;
  vehicleCompatibility: string[];
  description?: string;

  /**
   * Single price used for both retail/wholesale logic in the UI/actions.
   */
  price: number;

  /**
   * Stock handling:
   * - SINGLE: use quantity
   * - LEFT_RIGHT: use quantityLeft and quantityRight (and quantity stays 0)
   */
  orientation: ProductOrientation;
  quantity: number; // for SINGLE
  quantityLeft?: number; // for LEFT_RIGHT
  quantityRight?: number; // for LEFT_RIGHT

  reorderLevel: number;
  supplier?: mongoose.Types.ObjectId;
  images: string[];
  shop: mongoose.Types.ObjectId;
  storageLocation?: string;

  status: ProductStatus;
  totalSold: number;
  createdBy: mongoose.Types.ObjectId;
  createdAt: Date;
  updatedAt: Date;
}

const ProductSchema = new Schema<IProduct>(
  {
    name: { type: String, required: true, trim: true, index: "text" },

    /**
     * Auto-generated by the system on first save.
     */
    productCode: { type: String, required: true, unique: true, index: true, trim: true },

    category: { type: Schema.Types.ObjectId, ref: "Category", required: true, index: true },
    brand: { type: String, trim: true },
    vehicleCompatibility: [{ type: String, trim: true }],
    description: { type: String },

    price: { type: Number, required: true, min: 0 },

    orientation: {
      type: String,
      enum: ["SINGLE", "LEFT_RIGHT"],
      default: "SINGLE",
      required: true,
      index: true,
    },

    quantity: { type: Number, required: true, default: 0, min: 0, index: true },
    quantityLeft: { type: Number, default: 0, min: 0, index: true },
    quantityRight: { type: Number, default: 0, min: 0, index: true },

    reorderLevel: { type: Number, default: 10, min: 0 },
    supplier: { type: Schema.Types.ObjectId, ref: "Supplier" },
    images: [{ type: String }],
    shop: { type: Schema.Types.ObjectId, ref: "Shop", required: true, index: true },
    storageLocation: { type: String, trim: true },

    status: {
      type: String,
      enum: ["ACTIVE", "INACTIVE", "DISCONTINUED"],
      default: "ACTIVE",
      index: true,
    },

    totalSold: { type: Number, default: 0 },
    createdBy: { type: Schema.Types.ObjectId, ref: "User", required: true },
  },
  { timestamps: true }
);

// Keep indexes aligned with removed fields.
ProductSchema.index({ name: "text", productCode: "text" });
ProductSchema.index({ category: 1, status: 1 });
ProductSchema.index({ shop: 1, status: 1 });

/**
 * Auto-generate productCode:
 * - Format: PROD-<shopId>-<yyyyMMdd>-<increment>
 * - Increment is approximated via a deterministic suffix from existing count.
 *
 * NOTE: This is a best-effort generation; for high concurrency we should replace with a
 * dedicated counter collection. For now it unblocks production changes.
 */
ProductSchema.pre("validate", async function (next) {
  if (!this.isNew) return next();
  if (this.productCode && this.productCode.trim().length > 0) return next();

  const shopId = this.shop?.toString?.() ?? "NA";
  const datePart = new Date().toISOString().slice(0, 10).replaceAll("-", "");
  const basePrefix = `PROD-${shopId}-${datePart}-`;

  try {
    const existingCount = await mongoose.models.Product.countDocuments({
      shop: this.shop,
      productCode: { $regex: `^${basePrefix}` },
    });

    this.productCode = `${basePrefix}${String(existingCount + 1).padStart(4, "0")}`;
    next();
  } catch (err) {
    next(err as Error);
  }
});

export const Product: Model<IProduct> =
  mongoose.models.Product || mongoose.model<IProduct>("Product", ProductSchema);
